require("modules.monitors")
require("modules.environment")
require("modules.binds")
require("modules.autostart")
require("modules.decorations")
require("modules.layout")
require("modules.input")
require("modules.windowrules")
require("modules.miscellaneous")
require("modules.workspaces")
-- require("modules.permissions")